### ISSUE TITLE
BLE version ?

### ISSUE THREAD

**Issue by SeByDocKy** [KinDR007/VictronSmartShunt-ESPHOME#23]
Hi thanks for your great job to ESPhomify this Victron device. Seems Victron released the BLE protocol:
https://community.victronenergy.com/questions/93919/victron-bluetooth-ble-protocol-publication.html

Maybe there is a hope to add it in your current implementation ?

Sébastien

**Comment by XtremeOwnageDotCom** [comment]
That would be fantastic, being able to poll everything through BLE. For the people with a heavy victron investment, I am sure it would be of great value.

**Comment by KinDR007** [comment]
Currently only VE.Direct port is supported. Expansion to BLE variant is not planned yet
