### ISSUE TITLE
Victron BMV 700

### ISSUE THREAD

**Issue by MrJoki007** [KinDR007/VictronSmartShunt-ESPHOME#28]
Hello,
i just wanted to ask if the victron BMV 700 is supported.
Victron itself says that the smartshunt is a BMV 712 just without display and potential free relay.
The BMV 700 is a BMV 712, just without bluetooth and the ability to measure the middle voltage of a battery bank.
So it should not be so hard to support it, if it doesnt work right now, should it?

**Comment by KinDR007** [comment]
Yes, it is supported, however, I cannot guarantee that all values ​​will be read, even if it is likely
