### ISSUE TITLE
Add MQTT and global throttle?

### ISSUE THREAD

**Issue by billjuv** [KinDR007/VictronSmartShunt-ESPHOME#30]
I had no problem adding the setup info and connecting to my MQTT broker to my ESP32 but could not find anywhere that ESPHome would allow me to add a global throttle. Rather than add a throttle to each topic, I ended up using your VictronMPPT-ESPHOME/smartshunt-esp8266-example.yaml and modifying it for an ESP32 (it's working great even though I find the MQTT topic structure to be rather long-winded).

I tried this first as I only have the SmartShunt and was using the ESP32 but it didn't suit my needs without being able to throttle down the runaway messages I was getting.

**Comment by WZBFL** [comment]
Same "Poblem" here. On MPPT Code it's possible to use "throttle", but same code on shunt gets an error message.

**Comment by KinDR007** [comment]
Use MPPT lib to work with SmartShunts and BMV

**Comment by WZBFL** [comment]
Good idea, I already swapped this lib. It’s a bit confusing to have two different Von meinem Mobiltelefon gesendetAm 14/08/2023 um 18:02 schrieb Jiří Bětuňák ***@***.***>:﻿
Use MPPT lib to work with SmartShunts and BMV
