### ISSUE TITLE
BMV 712 Not sending info.

### ISSUE THREAD

**Issue by Bretthansenpc** [KinDR007/VictronSmartShunt-ESPHOME#31]
so everything works and uploads fine but I can not for the life of me get it to show anything from the BMV everything is unavailable I've changed pins and everything I can think of. I checked the voltage and I should be correct haha. Has anyone gotten anything other than the smart shunt to read?

**Comment by KinDR007** [comment]
Please try victron-mppt component 
Support both mppt and smartshunt/BMV

**Comment by Bretthansenpc** [comment]
Awesome Thanks. Still wouldn't work until I realized I had the GND soldered to 16 haha all good now works like a charm on the one you suggested :-)
