### ISSUE TITLE
Combine the mppt charger and smart shunt project?

### ISSUE THREAD

**Issue by syssi** [KinDR007/VictronSmartShunt-ESPHOME#6]
It is possible to combine both projects? Could you point out the differences of the protocols?

**Comment by KinDR007** [comment]
Check email

**Comment by syssi** [comment]
Using the same UART is no option. But it's possible to configure multiple UARTs. So we can load the victron component multiple times (one per UART). And we should inform the users to add a level shifter (if required).

**Comment by KinDR007** [comment]
so yes then that's a possibility
